// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project2api.Data;

#nullable disable

namespace project2api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240917231628_products")]
    partial class products
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("project2api.Model.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Mangsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("project2api.Model.EmployeeTask", b =>
                {
                    b.Property<int>("task_id")
                        .HasColumnType("int");

                    b.Property<int>("emp_id")
                        .HasColumnType("int");

                    b.HasKey("task_id", "emp_id");

                    b.HasIndex("emp_id");

                    b.ToTable("employeeTasks");
                });

            modelBuilder.Entity("project2api.Model.product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("dept_id")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("dept_id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("project2api.Model.worktask", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tasks");
                });

            modelBuilder.Entity("project2api.Model.EmployeeTask", b =>
                {
                    b.HasOne("project2api.Model.product", "emp")
                        .WithMany("emptaskes")
                        .HasForeignKey("emp_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project2api.Model.worktask", "task")
                        .WithMany("Ttasks")
                        .HasForeignKey("task_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("emp");

                    b.Navigation("task");
                });

            modelBuilder.Entity("project2api.Model.product", b =>
                {
                    b.HasOne("project2api.Model.Department", "dept")
                        .WithMany("employees")
                        .HasForeignKey("dept_id");

                    b.Navigation("dept");
                });

            modelBuilder.Entity("project2api.Model.Department", b =>
                {
                    b.Navigation("employees");
                });

            modelBuilder.Entity("project2api.Model.product", b =>
                {
                    b.Navigation("emptaskes");
                });

            modelBuilder.Entity("project2api.Model.worktask", b =>
                {
                    b.Navigation("Ttasks");
                });
#pragma warning restore 612, 618
        }
    }
}
